name: gethu_second_workflow
on: 
  workflow_dispatch:
  push:
  # pull_request:
  #   branches: 
  #     - main
  #     - dev/**
  #     - sample/**
env: 
  MONGO_DB_USER: "PodaVennai"
  MONGO_DB_PASSWORD: "SollaMudiyathu"
jobs: 
    first_job: 
        runs-on: windows-latest
        steps:
            - name: Welcome_Message
              run: echo "How are you team?"
            - name: Multi_Liner_script
              run: |
                echo "My first line"
                echo "My Second Line"
    
    second_job: 
        needs: first_job
        runs-on: ubuntu-latest
        steps:
            - name: Welcome_Message
              run: echo "How are you team?"
            - name: invoke_action
              uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            - name: Check Python Version 
              run: python --version 
            - name: Multi_Liner_script              
              run: |
                echo $MONGO_DB_USER
                echo $MONGO_DB_PASSWORD
                echo "${{ toJson(github.event.organization.login) }}" >> gethu.txt
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with: 
                path: gethu.txt