name: gethu_second_workflow
on: [push,workflow_dispatch]
jobs: 
    first_job: 
        runs-on: windows-latest
        steps:
            - name: Welcome_Message
              run: echo "How are you team?"
            - name: Multi_Liner_script
              run: |
                echo "My first line"
                echo "My Second Line"
    
    second_job: 
        needs: first_job
        runs-on: ubuntu-latest
        steps:
            - name: Welcome_Message
              run: echo "How are you team?"
            - name: invoke_action
              uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            - name: Check Python Version 
              run: python --version
            - name: Multi_Liner_script              
              run: |
                echo "My first line"
                echo "My Second Line"
                echo "${{ toJson(github.event.organization.login) }}"
            